"""Add RiscEvent model

Revision ID: 0cd91583b371
Revises: 3b4c5d6e7f8a
Create Date: 2025-11-21 18:26:19.588736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cd91583b371'
down_revision = '3b4c5d6e7f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risc_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('google_user_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('token_payload', sa.Text(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('action_taken', sa.String(length=255), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risc_events', schema=None) as batch_op:
        batch_op.create_index('idx_risc_user_processed', ['google_user_id', 'processed'], unique=False)
        batch_op.create_index(batch_op.f('ix_risc_events_google_user_id'), ['google_user_id'], unique=False)

    with op.batch_alter_table('data_source_connections', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('data_source_connections_organization_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('generated_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_generated_documents_organization'))
        batch_op.drop_index(batch_op.f('idx_generated_documents_source'))
        batch_op.drop_index(batch_op.f('idx_generated_documents_status'))
        batch_op.drop_index(batch_op.f('idx_generated_documents_workflow'))
        batch_op.drop_constraint(batch_op.f('generated_documents_organization_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('organization_features', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('organization_features_organization_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('signature_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_signature_requests_document'))
        batch_op.drop_index(batch_op.f('idx_signature_requests_status'))
        batch_op.drop_constraint(batch_op.f('signature_requests_organization_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('signature_requests_generated_document_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])
        batch_op.create_foreign_key(None, 'generated_documents', ['generated_document_id'], ['id'])

    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_templates_organization'))
        batch_op.drop_constraint(batch_op.f('templates_organization_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_users_email'))
        batch_op.drop_index(batch_op.f('idx_users_organization'))
        batch_op.drop_constraint(batch_op.f('users_organization_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('workflow_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_workflow_executions_workflow'))
        batch_op.drop_constraint(batch_op.f('workflow_executions_workflow_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'workflows', ['workflow_id'], ['id'])

    with op.batch_alter_table('workflow_field_mappings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('workflow_field_mappings_workflow_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'workflows', ['workflow_id'], ['id'])

    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_workflows_organization'))
        batch_op.drop_index(batch_op.f('idx_workflows_status'))
        batch_op.drop_constraint(batch_op.f('workflows_organization_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('workflows_organization_id_fkey'), 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_workflows_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_workflows_organization'), ['organization_id'], unique=False)

    with op.batch_alter_table('workflow_field_mappings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('workflow_field_mappings_workflow_id_fkey'), 'workflows', ['workflow_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('workflow_executions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('workflow_executions_workflow_id_fkey'), 'workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_workflow_executions_workflow'), ['workflow_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('users_organization_id_fkey'), 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_users_organization'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)

    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('templates_organization_id_fkey'), 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_templates_organization'), ['organization_id'], unique=False)

    with op.batch_alter_table('signature_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('signature_requests_generated_document_id_fkey'), 'generated_documents', ['generated_document_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('signature_requests_organization_id_fkey'), 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_signature_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_signature_requests_document'), ['generated_document_id'], unique=False)

    with op.batch_alter_table('organization_features', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('organization_features_organization_id_fkey'), 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('generated_documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('generated_documents_organization_id_fkey'), 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_generated_documents_workflow'), ['workflow_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_generated_documents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_generated_documents_source'), ['source_object_type', 'source_object_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_generated_documents_organization'), ['organization_id'], unique=False)

    with op.batch_alter_table('data_source_connections', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('data_source_connections_organization_id_fkey'), 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('risc_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risc_events_google_user_id'))
        batch_op.drop_index('idx_risc_user_processed')

    op.drop_table('risc_events')
    # ### end Alembic commands ###
