"""Add user settings models

Revision ID: 648d6d69e67d
Revises: o5p6q7r8s9t0
Create Date: 2025-12-14 22:05:47.316711

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '648d6d69e67d'
down_revision = 'o5p6q7r8s9t0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('key_prefix', sa.String(length=10), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index('idx_api_keys_org_id', ['organization_id'], unique=False)
        batch_op.create_index('idx_api_keys_user_id', ['user_id'], unique=False)

    op.create_table('global_field_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_system', sa.String(length=50), nullable=False),
    sa.Column('target_system', sa.String(length=50), nullable=False),
    sa.Column('mappings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('login_method', sa.String(length=50), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.create_index('idx_login_history_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_login_history_user_id', ['user_id'], unique=False)

    op.create_table('user_2fa',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('secret', sa.String(length=255), nullable=True),
    sa.Column('backup_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_notification_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=True),
    sa.Column('email_document_generated', sa.Boolean(), nullable=True),
    sa.Column('email_document_signed', sa.Boolean(), nullable=True),
    sa.Column('email_workflow_executed', sa.Boolean(), nullable=True),
    sa.Column('email_workflow_failed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('date_format', sa.String(length=20), nullable=True),
    sa.Column('time_format', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('units', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_user_sessions_token', ['session_token'], unique=False)
        batch_op.create_index('idx_user_sessions_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('ai_generation_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_ai_mapping_workflow'))

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.alter_column('workflows_used',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('pkce_verifiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_pkce_expires_at'))
        batch_op.drop_index(batch_op.f('idx_pkce_state'))
        batch_op.create_index(batch_op.f('ix_pkce_verifiers_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pkce_verifiers_state'), ['state'], unique=False)

    with op.batch_alter_table('workflow_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_workflow_node_webhook_token'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_workflow_node_webhook_token'), ['webhook_token'], unique=True)

    with op.batch_alter_table('pkce_verifiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pkce_verifiers_state'))
        batch_op.drop_index(batch_op.f('ix_pkce_verifiers_expires_at'))
        batch_op.create_index(batch_op.f('idx_pkce_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('idx_pkce_expires_at'), ['expires_at'], unique=False)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.alter_column('workflows_used',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('ai_generation_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_ai_mapping_workflow'), ['workflow_id'], unique=False)

    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_user_sessions_user_id')
        batch_op.drop_index('idx_user_sessions_token')

    op.drop_table('user_sessions')
    op.drop_table('user_preferences')
    op.drop_table('user_notification_preferences')
    op.drop_table('user_2fa')
    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.drop_index('idx_login_history_user_id')
        batch_op.drop_index('idx_login_history_created_at')

    op.drop_table('login_history')
    op.drop_table('global_field_mappings')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index('idx_api_keys_user_id')
        batch_op.drop_index('idx_api_keys_org_id')

    op.drop_table('api_keys')
    # ### end Alembic commands ###
