"""Add better-auth columns to users and fix execution FK

Revision ID: 677720517350
Revises: y4z5a6b7c8d9
Create Date: 2025-12-24 17:58:09.065088

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '677720517350'
down_revision = 'y4z5a6b7c8d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('execution_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_logs_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_logs_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_logs_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_logs_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('execution_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('app_key', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('action_key', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('error_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('duration_ms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('step_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.alter_column('step_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.alter_column('error_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('ix_execution_steps_execution_id'))
        batch_op.drop_index(batch_op.f('ix_execution_steps_execution_position'))
        batch_op.drop_index(batch_op.f('ix_execution_steps_status'))
        batch_op.create_index('idx_execution_step_execution', ['execution_id'], unique=False)
        batch_op.create_index('idx_execution_step_position', ['execution_id', 'position'], unique=False)
        batch_op.create_index('idx_execution_step_status', ['execution_id', 'status'], unique=False)
        batch_op.drop_column('error_message')
        batch_op.drop_column('execution_time_ms')
        batch_op.drop_column('retry_count')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('signature_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_signature_request_execution'))

    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.alter_column('google_file_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('google_file_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_anonymous', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.Text(), nullable=True))
        batch_op.alter_column('organization_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('workflow_datastores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datastore_org_id'))
        batch_op.create_index(batch_op.f('ix_workflow_datastores_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_datastores_scope_id'), ['scope_id'], unique=False)

    with op.batch_alter_table('workflow_executions', schema=None) as batch_op:
        batch_op.alter_column('progress',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('correlation_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('current_node_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using='current_node_id::uuid')
        batch_op.drop_index(batch_op.f('idx_execution_status_workflow'))
        batch_op.drop_index(batch_op.f('idx_execution_temporal_workflow_id'))

    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.alter_column('visibility',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'private'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.alter_column('visibility',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'private'::character varying"))

    with op.batch_alter_table('workflow_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_execution_temporal_workflow_id'), ['temporal_workflow_id'], unique=True)
        batch_op.create_index(batch_op.f('idx_execution_status_workflow'), ['workflow_id', 'status'], unique=False)
        batch_op.alter_column('current_node_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('correlation_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('progress',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('workflow_datastores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_datastores_scope_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_datastores_organization_id'))
        batch_op.create_index(batch_op.f('ix_datastore_org_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('organization_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_column('image')
        batch_op.drop_column('is_anonymous')
        batch_op.drop_column('email_verified')

    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.alter_column('google_file_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('google_file_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('signature_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_signature_request_execution'), ['workflow_execution_id'], unique=False)

    with op.batch_alter_table('execution_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('retry_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('execution_time_ms', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_index('idx_execution_step_status')
        batch_op.drop_index('idx_execution_step_position')
        batch_op.drop_index('idx_execution_step_execution')
        batch_op.create_index(batch_op.f('ix_execution_steps_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_steps_execution_position'), ['execution_id', 'position'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_steps_execution_id'), ['execution_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('error_details',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.alter_column('step_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('step_metadata')
        batch_op.drop_column('duration_ms')
        batch_op.drop_column('error_code')
        batch_op.drop_column('action_key')
        batch_op.drop_column('app_key')

    with op.batch_alter_table('execution_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_execution_logs_level'))
        batch_op.drop_index(batch_op.f('ix_execution_logs_domain'))
        batch_op.drop_index(batch_op.f('ix_execution_logs_correlation_id'))

    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_timestamp'))

    # ### end Alembic commands ###
